Stops updating datastore when too many services are down
m-lab/mlab-ns pull request #251
Opened 2021-04-09 19:09 UTC by nkinkade

This small PR introduces a check to be sure that more than a certain percentage of services are reported as online before using monitoring data to update service state. This PR is intended to resolve https://github.com/m-lab/mlab-ns/issues/243.

We currently have [numerous NDT-related alerts](https://github.com/m-lab/prometheus-support/blob/master/config/federation/prometheus/alerts.yml#L213) that will notify us when less than 90% of NDT services are reported as online for IPv4 (<75% for IPv6). The statically configured thresholds in the PR are well below the alert thresholds, meaning that we will receive alerts about a problem before mlab-ns starts disregarding monitoring results and serving stale data.

2021-04-12 17:40 UTC, stephen-soltesz requested changes
The logic looks okay. Please add at least a minimal unit test to verify intended behavior.

> *[Reviewable](https://reviewable.io/reviews/m-lab/mlab-ns/251#-:-MY69hZ49_BLYQ_cLGk7:btd2sj4)* status: 0 of 1 LGTMs obtained (waiting on @nkinkade)

___
*[server/mlabns/handlers/update.py, line 382 at r1](https://reviewable.io/reviews/m-lab/mlab-ns/251#-MY69IWTE_ID5gD9j8Ho:-MY69IWTE_ID5gD9j8Hp:bh1q097) ([raw file](https://github.com/m-lab/mlab-ns/blob/0f40a1b9bea58277a277b5b9ef0506c6d018a321/server/mlabns/handlers/update.py#L382)):*
> ```Python
>                             tool_id, address_family)
>                         continue
>                 elif tool.status_source == 'nagios':
> ```

In a future PR, consider cleaning up these branches to help make the logic a little easier to follow.
___
*[server/mlabns/handlers/update.py, line 498 at r1](https://reviewable.io/reviews/m-lab/mlab-ns/251#-MY69-XW13V-SaF7RWpI:-MY69-XW13V-SaF7RWpJ:bi5fbm8) ([raw file](https://github.com/m-lab/mlab-ns/blob/0f40a1b9bea58277a277b5b9ef0506c6d018a321/server/mlabns/handlers/update.py#L498)):*
> ```Python
>                 logging.error('Failed to update sliver status in memcache.')
> 
>     def is_slice_status_okay(self, slice_status, tool_id, family):
> ```

Please provide unit test.


<!-- Sent from Reviewable.io -->

2021-04-20 17:51 UTC, nkinkade reviewed
@stephen-soltesz: I have made some modifications in response to your comments. PTAL?

> *[Reviewable](https://reviewable.io/reviews/m-lab/mlab-ns/251#-:-MYkNjUz29t7SXZzqF4y:b-v2gpk2)* status: 0 of 1 LGTMs obtained (waiting on @stephen-soltesz)

___
*[server/mlabns/handlers/update.py, line 382 at r1](https://reviewable.io/reviews/m-lab/mlab-ns/251#-MY69IWTE_ID5gD9j8Ho:-MYkMCPI4Um34k80Jy-B:b-4e8fes) ([raw file](https://github.com/m-lab/mlab-ns/blob/0f40a1b9bea58277a277b5b9ef0506c6d018a321/server/mlabns/handlers/update.py#L382)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

In a future PR, consider cleaning up these branches to help make the logic a little easier to follow.
</blockquote></details>

We should. I've been hoping that Locate v2 was going to be going to the point we could retire mlab-ns and not have to worry about touching it any longer (including cleaning up the Nagios stuff).
___
*[server/mlabns/handlers/update.py, line 498 at r1](https://reviewable.io/reviews/m-lab/mlab-ns/251#-MY69-XW13V-SaF7RWpI:-MYkMQtfEY39RX2Mzrnc:bmushrb) ([raw file](https://github.com/m-lab/mlab-ns/blob/0f40a1b9bea58277a277b5b9ef0506c6d018a321/server/mlabns/handlers/update.py#L498)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Please provide unit test.
</blockquote></details>

I've added a basic unit test. I had to mock everything under to the sun to get it working, though. Maybe there is a way to mock less? The basic idea of the unit test is to pass a slice status with more than 75% of the "slivers" online, and then verify that `update_sliver_tools_status()` was called. And then the opposite case, where only 50% are online, and verifying that that same function was no called.


<!-- Sent from Reviewable.io -->

2021-04-20 17:53 UTC, nkinkade reviewed
Oh, hold... I just noticed an error in the unit test.

> *[Reviewable](https://reviewable.io/reviews/m-lab/mlab-ns/251#-:-MYkPVasDC8HK47G29oK:bh7qfm5)* status: 0 of 1 LGTMs obtained (waiting on @stephen-soltesz)



<!-- Sent from Reviewable.io -->

2021-04-20 21:33 UTC, nkinkade reviewed
@stephen-soltesz: I believe I have fixed the issues with the unit test I added. PTAL?

> *[Reviewable](https://reviewable.io/reviews/m-lab/mlab-ns/251#-:-MYlBrt64Eg4-PTGM_dd:b-a29vns)* status: 0 of 1 LGTMs obtained (waiting on @stephen-soltesz)



<!-- Sent from Reviewable.io -->

2021-04-20 21:49 UTC, stephen-soltesz approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/m-lab/mlab-ns/251#-:-MYlFfpz3Bb2UylNT22x:bnfp4nl)* status: :shipit: complete! 1 of 1 LGTMs obtained (waiting on @nkinkade)

___
*[server/mlabns/handlers/update.py, line 498 at r1](https://reviewable.io/reviews/m-lab/mlab-ns/251#-MY69-XW13V-SaF7RWpI:-MYlEkRo8dldsVLWDY-P:bbew0hr) ([raw file](https://github.com/m-lab/mlab-ns/blob/0f40a1b9bea58277a277b5b9ef0506c6d018a321/server/mlabns/handlers/update.py#L498)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

I've added a basic unit test. I had to mock everything under to the sun to get it working, though. Maybe there is a way to mock less? The basic idea of the unit test is to pass a slice status with more than 75% of the "slivers" online, and then verify that `update_sliver_tools_status()` was called. And then the opposite case, where only 50% are online, and verifying that that same function was no called.
</blockquote></details>

My original intention was just a unit test for this function. What you've done is also good. But, it's more than I thought I was asking you for. I guess we don't have coveralls reports for python?


<!-- Sent from Reviewable.io -->

2021-04-20 22:01 UTC, nkinkade reviewed
> *[Reviewable](https://reviewable.io/reviews/m-lab/mlab-ns/251)* status: :shipit: complete! 1 of 1 LGTMs obtained (waiting on @stephen-soltesz)

___
*[server/mlabns/handlers/update.py, line 498 at r1](https://reviewable.io/reviews/m-lab/mlab-ns/251#-MY69-XW13V-SaF7RWpI:-MYlHKq7AA2HrNm94VxT:b-j1mkf0) ([raw file](https://github.com/m-lab/mlab-ns/blob/0f40a1b9bea58277a277b5b9ef0506c6d018a321/server/mlabns/handlers/update.py#L498)):*
I considered only covering the `is_slice_status_okay()` method, but it didn't seem as safe to me. That method is very small and simple, but what we really want to ensure is that `update_sliver_tools_status` does **not** get called when that first function returns false, and writing the test the way I did, I believe, gives us some confidence that not only does `is_slice_status_okay()` working okay, but also that `update_sliver_tools_status` doesn't get called. It's terrible mess of mocks being initiated in various ways, but then again, the other tests in the file are similarly ugly, with Michael even adding this TODO:

>  # TODO(mtlynch): Redesign SiteRegistrationHandler to be more
>  # test-friendly and rely less on patching


<!-- Sent from Reviewable.io -->

2021-04-20 22:01 UTC, merged